### ISSUE TITLE
problem about rusult

### ISSUE THREAD

**Issue by hengliang8** [ymli39/DeepSEED-3D-ConvNets-for-Pulmonary-Nodule-Detection#14]
I use trained your network, but the test result is about 0.72. 
the batch size is 16
the detp I set is 0.3
the nmsthresh is (0.01, 0.25, 0. 75) 
I want to know your settings to get your awesome results. 
wish for your reply.

**Comment by hengliang8** [comment]
I also use the model your submit 'detector_207. ckpt', and use the test id in your  'predanno0.3.csv'
but the result is about 0.7
wish for your reply

**Comment by ymli39** [comment]
Sorry about late response, I used nmsthresh of 0.1 and detp of 0.3. I noticed a bug when I tried to download the evaluation script from LUNA16 website and I think it is probably due to the linux system that the xlsx file behaves different than an excel that in my testing code it skips all the results starts from 0. So instead of inputting 001, it inputs 1, while the gt has the id 001. I change corresponding code to make it consist with gt. But this might varies depending on your computer system. This is the major reason I got undermined results at first.

**Comment by shakjm** [comment]
> Sorry about late response, I used nmsthresh of 0.1 and detp of 0.3. I noticed a bug when I tried to download the evaluation script from LUNA16 website and I think it is probably due to the linux system that the xlsx file behaves different than an excel that in my testing code it skips all the results starts from 0. So instead of inputting 001, it inputs 1, while the gt has the id 001. I change corresponding code to make it consist with gt. But this might varies depending on your computer system. This is the major reason I got undermined results at first.

Hi Mr Li, 

I actually was only able to get 0.844 CPM and would really appreciate it if you could let me know if using your defined IDs would help? I used the original annotations and seriesuids because it my files weren't renamed to the IDs when preprocessing them.
